import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import {Poppins} from "next/font/google"
import { ToasterProvider } from "@/provider/Toaster";

const inter = Poppins({ subsets: ["latin"] , weight : ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToasterProvider/>
        {children}
        </body>
    </html>
  );
}
